GET http://localhost:3000/todo/todos?limit=12&offset=0

###

GET http://localhost:3000/todo/todos/32

###

POST http://localhost:3000/todo/create
Content-Type: application/json

{
  "text": ""
}

###

GET http://localhost:3000/fibonacci

###

GET http://localhost:3000/fibonacci/100

###

POST http://localhost:3000/send-message
Content-Type: application/json

{
  "sender": "../czalbi",
  "message": "test"
}

###

PUT http://localhost:3000/todo/todos/5
Content-Type: application/json

{
  "text": "az új feladat czalbinak"
}

###

DELETE http://localhost:3000/todo/todos/0